//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsefDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginInformation
    {
        public string Username { get; set; }
        public byte[] UserPassword { get; set; }
        public byte[] UserSalt { get; set; }
        public string UserEmail { get; set; }
    }
}
