//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubHasTitle
    {
        public int ClubAndTitleID { get; set; }
        public int ClubID { get; set; }
        public int TitleID { get; set; }
        public string DateOfAcquisition { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Title Title { get; set; }
    }
}
