//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractID { get; set; }
        public int ClubID { get; set; }
        public int PlayerID { get; set; }
        public Nullable<System.DateTime> ValidUntill { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<decimal> AnnualSalary { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Player Player { get; set; }
    }
}
